version: '3'

services:
  where-it-go-main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: where-it-go-main
    #    restart: always
    volumes:
      - ./config:/Serve/config
    ports:
      - "19083:8080"